### ISSUE TITLE
Working with HL-L2335D

### ISSUE THREAD

**Issue by dlxmax** [QORTEC/brlaser#4]
Thanks so much for this! All works well (2-sided printing) with the HL-L2335D as well.

Device: uri = usb://Brother/HL-L2335D%20series?serial=E79562G0N714273
        class = direct
        info = Brother HL-L2335D series
        make-and-model = Brother HL-L2335D series
        device-id = MFG:Brother;CMD:PJL,HBP;MDL:HL-L2335D series;CLS:PRINTER;CID:Brother Laser Type1;
        location =

**Comment by QORTEC** [comment]
Thank you for your report, I've added your printer to my pull request pdewacht#179 in commit fed695c5e7de5432900624bda42578a4a88e081c.

On the [Owl-Maintain/brlaser](https://github.com/Owl-Maintain/brlaser) fork you'll see that `v6.2.6` was just tagged and released and your printer is included.
